Correção: CORS
CEIP-USP/backend pull request #12
Opened 2021-12-02 20:08 UTC by lfujiwara

Co-authored-by: Ian Galvao <ian.galvao@usp.br>

2021-12-03 18:08 UTC, jooaodanieel requested changes

2021-12-03 18:08 UTC, jooaodanieel commented on src/app/web/cors.ts
> +};
O middleware do CORS aceita uma função, se não me engano. O que você implementou aqui inverte a lógica dos plugins do express, porque recebe o app como argumento. A lógica em si de pegar do env e tal tá ok, mas essa inversão me incomoda.

2021-12-03 22:06 UTC, lfujiwara commented on src/app/web/cors.ts
> +};
Eu só quis isolar o código que cuida disso na real, não criei isso como plugin do express especificamente, só como uma função que faz as alterações necessárias em um app, pra não ter que gerar a closure em outro lugar, e daí na main pegar essa closure e chamar o `cors({origin: closure})`.
Acho que dá pra alterar isso fazendo essa função devolver só o objeto dentro do app.use nesse trecho, daí na main faz com `app.use(customCors())`.

2021-12-07 12:16 UTC, jooaodanieel commented on src/app/web/cors.ts
> +};
@lfujiwara faz essa alteração, porque o `index` não tem problema ficar cheio de coisas porque é justamente o ponto de conexão de tudo. Com a closure separada num arquivo, fica mais organizado (como já está), porém passa a seguir a lógica dos plugins do express (que não está).

2021-12-07 20:18 UTC, jooaodanieel approved these changes

2021-12-07 21:03 UTC, merged